# Generated by Django 4.0.2 on 2022-02-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
